parameters:

    #
    # Services
    #
    elcodi.core.coupon.service.coupon_manager.class: Elcodi\Component\Coupon\Services\CouponManager

    #
    # Factories
    #
    elcodi.core.coupon.factory.coupon.class: Elcodi\Component\Coupon\Factory\CouponFactory

    #
    # Generators
    #
    elcodi.core.referral_program.generator.coupon_code_generator.class: Elcodi\Component\Coupon\Generator\CouponCodeGenerator

    #
    # Event Dispatchers
    #
    elcodi.core.coupon.event_dispatchers.coupon.class: Elcodi\Component\Coupon\EventDispatcher\CouponEventDispatcher

    #
    # Event Listeners
    #
    elcodi.core.coupon.event_listener.coupon.class: Elcodi\Component\Coupon\EventListener\CouponEventListener
