services:

    #
    # Event Dispatchers
    #
    elcodi.core.coupon.event_dispatchers.coupon:
        class: %elcodi.core.coupon.event_dispatchers.coupon.class%
        arguments:
            event_dispatcher: @event_dispatcher
