services:

    #
    # Factories
    #

    #
    # Factory for entity coupon
    #
    elcodi.core.coupon.factory.coupon:
        class: %elcodi.core.coupon.factory.coupon.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.coupon.entity.coupon.class%"]]

    elcodi.factory.coupon:
        alias: elcodi.core.coupon.factory.coupon
