services:

    #
    # Factories
    #

    #
    # Factory for entity coupon
    #
    elcodi.factory.coupon:
        class: %elcodi.factory.coupon.class%
        parent: elcodi.factory.abstract.purchasable
        calls:
            - [setEntityNamespace, ["%elcodi.entity.coupon.class%"]]
