services:

    #
    # Form Types
    #
    elcodi.core.coupon.form_type.coupon:
        class: %elcodi.core.coupon.form_type.coupon.class%
        tags:
            - { name: form.type, alias: elcodi_core_form_types_coupon }
