services:

    #
    # Repositories
    #

    #
    # Repository for entity coupon
    #
    elcodi.repository.coupon:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.coupon.entity.coupon.class%
