services:

    #
    # Repositories
    #

    #
    # Repository for entity coupon
    #
    elcodi.repository.coupon:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.coupon.entity.coupon.class% ]
