services:

    #
    # Services
    #
    elcodi.manager.coupon:
        class: %elcodi.manager.coupon.class%
        arguments:
            - @elcodi.factory.coupon
            - @elcodi.generator.random_string
