services:

    #
    # Services
    #
    elcodi.coupon_manager:
        class: %elcodi.coupon_manager.class%
        arguments:
            coupon_factory: @elcodi.factory.coupon
            coupon_code_generator: @elcodi.generator.random_string
