services:

    #
    # Services
    #
    elcodi.manager.coupon:
        class: %elcodi.manager.coupon.class%
        arguments:
            coupon_factory: @elcodi.factory.coupon
            coupon_code_generator: @elcodi.generator.random_string
